application: nuitinfo11
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline/handlers.py

- url: /stylesheet
  static_dir: CSS

- url: /.*
  script: buddha.py
  login: required

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

