application: nuitinfo11
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /stylesheet
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: main.py

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

